version: "2.1"

services:
    db:
        build: db/
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - ./var/mysql:/var/lib/mysql

    gateway_db:
        image: cassandra:2.2
        volumes:
            - ./var/cassandra:/var/lib/cassandra

    gateway:
        image: kong
        links:
            - gateway_db
            - service.api.auth
            - service.model.user
        expose:
            - 7946
            - 7946/udp
        environment:
            KONG_DATABASE: cassandra
            KONG_CASSANDRA_CONTACT_POINTS: gateway_db
            KONG_PROXY_LISTEN: 0.0.0.0:80

    service.api.auth:
        image: deshboard/auth-api-service
        links:
            - service.model.user
        environment:
            SERVICE_MODEL_USER: service.model.user
            SIGNING_KEY: change_this

    service.model.user:
        image: deshboard/user-model-service
        links:
            - db
        environment:
            DATABASE_TYPE: mysql
            DATABASE_HOST: db
            DATABASE_PORT: 3306
            DATABASE_USER: service_model_user
            DATABASE_PASS: service_model_user
            DATABASE_DB: service_model_user
