version: "2.1"

services:
    gateway_db_check:
        image: jwilder/dockerize
        command: dockerize -wait tcp://gateway_db:9042 -timeout 120s
        links:
            - gateway_db

    gateway_check:
        image: jwilder/dockerize
        command: dockerize -wait http://gateway:8001 -timeout 200s
        links:
            - gateway

    gateway_init:
        build: gateway_init/
        links:
            - gateway
        environment:
            KONG_ADMIN_API: "gateway:8001"

    db_check:
        image: jwilder/dockerize
        command: dockerize -wait tcp://db:3306 -timeout 120s
        links:
            - db

    service.model.user.migration:
        image: deshboard/user-model-service:latest-migration
        links:
            - db
        environment:
            LIQUIBASE_USERNAME: root
            LIQUIBASE_PASSWORD: ""
            LIQUIBASE_URL: jdbc:mysql://db/service_model_user
